### ISSUE TITLE
How to get the illumination effect map Gi？

### ISSUE THREAD

**Issue by HAHAkun** [jinyeying/night-enhancement#11]
I'm sorry to bother you.I don't know how to get the illumination effect map Gi in Section 3.1 of your paper.If possible, would it be convenient for you to share this part of the code?

**Comment by jinyeying** [comment]
> I'm sorry to bother you.I don't know how to get the illumination effect map Gi in Section 3.1 of your paper.If possible, would it be convenient for you to share this part of the code?

For the light-effects layer, we use a light-effects map G0, computed using the relative smoothness technique from previous works.
