### ISSUE TITLE
How to get light-effects map?

### ISSUE THREAD

**Issue by Yueziyu** [jinyeying/night-enhancement#12]
Thank you for presenting such interesting work.  I have some questions about how to get the light-effects map.  G<sub>i</sub> in Formula 2 of the paper is obtained by the relative smoothness technique. May I ask whether the septRelSmo function provided by Yu Li is used in the process of calculating G<sub>i</sub>? And do you need to multiply the decomposed image by 2 to enlarge the pixel values? Thank you！

**Comment by jinyeying** [comment]
> 

we use septRelSmo function to obtain G0, the guidance of G
