### ISSUE TITLE
cam attentionmap

### ISSUE THREAD

**Issue by 838959823** [jinyeying/night-enhancement#20]
论文中说将feature map取平均后可以得到attentionmap，但是代码里面却是写着torch.sum，这是为什么呢

**Comment by jinyeying** [comment]
> 论文中说将feature map取平均后可以得到attentionmap，但是代码里面却是写着torch.sum，这是为什么呢
The attention map is computed as the sum of the weighted multi-channel feature map, not the mean. The attention at each spatial position is the sum of the weighted features at that position.
