### ISSUE TITLE
图像分解训练代码

### ISSUE THREAD

**Issue by psj-jerry** [jinyeying/night-enhancement#21]
Hi, may I ask how the first half of the layer decomposition network is implemented? I feel in the figure of your paper that it is derived from training the deep network, but you put out the code for matlab direct decomposition and I feel some inconsistency? Can you give me the full code of the layer decomposition network?

**Comment by jinyeying** [comment]
It is from the deep network; we use the Matlab decomposition as initial guidance in Eq.2. 
The code will release later.

**Comment by psj-jerry** [comment]
> It is from the deep network; we use the Matlab decomposition as initial guidance in Eq.2. The code will release later.

Thank you! Looking forward to the code open source soon
