### ISSUE TITLE
train code

### ISSUE THREAD

**Issue by dreaming12580** [jinyeying/night-enhancement#24]
can share  train code for public ?

**Comment by xiezhang666** [comment]
same question ...

**Comment by Hhxxhj** [comment]
same question！

**Comment by qiuchentan** [comment]
same question！

**Comment by changyangmimeng** [comment]
same question！

**Comment by Zewhy567** [comment]
same question！

**Comment by changyangmimeng** [comment]
您的邮件已收到！谢谢！

**Comment by chenccxx** [comment]
same question！

**Comment by changyangmimeng** [comment]
您的邮件已收到！谢谢！

**Comment by icearbiter** [comment]
same question. Thank you very much!

**Comment by icearbiter** [comment]
> 您的邮件已收到！谢谢！
您收到train的代码了么？如果您有训练代码的样例，可以请您分享给我一下么？非常感谢！

**Comment by icearbiter** [comment]
> 您的邮件已收到！谢谢！

您有train的代码么？如果有的话，您能发我一份么？非常感谢！

**Comment by zgbuct** [comment]
same question！

**Comment by changyangmimeng** [comment]
您的邮件已收到！谢谢！

**Comment by frenshman** [comment]
your model is so robust, can u share train code for public !

**Comment by changyangmimeng** [comment]
您的邮件已收到！谢谢！

**Comment by hwgao1101** [comment]
same question! can share train code?  thanks

**Comment by jm-xiong** [comment]
same question！

**Comment by changyangmimeng** [comment]
您的邮件已收到！谢谢！

**Comment by rongakushin** [comment]
Same question! Could you share the training code? Thanks!

**Comment by changyangmimeng** [comment]
您的邮件已收到！谢谢！

**Comment by changyangmimeng** [comment]
您的邮件已收到！谢谢！

**Comment by Bruce-W12138** [comment]
same question

**Comment by changyangmimeng** [comment]
您的邮件已收到！谢谢！

**Comment by JoeLeelyf** [comment]
same question! can share train code? thanks
