### ISSUE TITLE
这文章忽悠人的

### ISSUE THREAD

**Issue by pandayuanyu** [jinyeying/night-enhancement#26]
所谓的三个cnn layers分解实际是靠matlab代码完成的，文章里的图3中的L和R分解出来连灯都没有了是吧？后面的增强部分就是抄袭enlightengan。垃圾文章

**Comment by jinyeying** [comment]
> 所谓的三个cnn layers分解实际是靠matlab代码完成的，文章里的图3中的L和R分解出来连灯都没有了是吧？后面的增强部分就是抄袭enlightengan。垃圾文章
三个cnn layers分解实际是靠matlab代码完成的，然后给cnn做的l1约束，文章里也是这么写的啊。
图3中的L和R分解出来连灯都没有了是一个潜在的问题，你可以提高呀。后续我们mm的文章有对灯的constraint。

后面的增强，和enlightengan一样都是cyclegan based的。code里面的cam attention enlightengan没有的吧？

**Comment by pandayuanyu** [comment]
所以你分解的cnn的训练网络呢？你的图2为什么又有灯呢？不会图4是拿着PS出来的吧？一堆损失函数的文章一定是烂文章，垃圾就是垃圾。

**Comment by jinyeying** [comment]
> 所以你分解的cnn的训练网络呢？你的图2为什么又有灯呢？不会图4是拿着PS出来的吧？一堆损失函数的文章一定是烂文章，垃圾就是垃圾。

哥，stage1有可能分错，不代表stage2就是错的啊。stage2 data-driven的。可以精心设计下data。
grayword loss对图四就能work。

我要是真会ps就好了。科研就不至于这么辛苦了。

如果不喜欢，建议别浪费太多时间。

**Comment by jinyeying** [comment]
> 所以你分解的cnn的训练网络呢？你的图2为什么又有灯呢？不会图4是拿着PS出来的吧？一堆损失函数的文章一定是烂文章，垃圾就是垃圾。

后续有IJCAI2022 From Generation to Suppression: Towards Effective Irregular glow suppression for Nighttime Visibility Enhancement，还有Slab，我们组其他人有更好的工作。
