### ISSUE TITLE
光效应test运行后没有输出结果

### ISSUE THREAD

**Issue by DAXIANGBIZICHANGJINGLU** [jinyeying/night-enhancement#27]
下载好作者提供的权重后，测试光效应效果，light-effects-output目录下并没有输出

**Comment by jinyeying** [comment]
> 下载好作者提供的权重后，测试光效应效果，light-effects-output目录下并没有输出
https://www.bilibili.com/video/BV1Nv4y1B7Mp/?spm_id_from=333.999.0.0&vd_source=8ae1cd92e40b380c0296eb6843da79a4
可以根据这个b站讲解，学习一下，如何test。

**Comment by clue3clue32** [comment]
png格式的读入似乎有问题

**Comment by jinyeying** [comment]
> png格式的读入似乎有问题

后面代码应该是改了,  应该没有问题. https://github.com/jinyeying/night-enhancement/blob/d6ec06f95e68d84edc5ca71135d0fd090abe559d/main.py#L37
