### ISSUE TITLE
如何通过输入直接得到强光抑制和暗光增强的输出J-refine

### ISSUE THREAD

**Issue by swjtu-ljc** [jinyeying/night-enhancement#29]
你好：感谢你的优秀工作！
readme中可以看到暗光增强和强光抑制分别作为两个部分进行测试，[Decomposition3](https://github.com/jinyeying/night-enhancement/blob/main/decomposition_code/demo_decomposition.m)这里面写到运行demo_decomposition.m可以获得J-init
请问如何直接通过输入得到强光抑制和暗光增强的输出J-refine呢，正如您在论文里面提到的结构图
![image](https://github.com/user-attachments/assets/fd4479e1-ae8a-4a83-aea8-f2663025f4d0)

**Comment by jinyeying** [comment]
> 你好：感谢你的优秀工作！ readme中可以看到暗光增强和强光抑制分别作为两个部分进行测试，[Decomposition3](https://github.com/jinyeying/night-enhancement/blob/main/decomposition_code/demo_decomposition.m)这里面写到运行demo_decomposition.m可以获得J-init 请问如何直接通过输入得到强光抑制和暗光增强的输出J-refine呢，正如您在论文里面提到的结构图 ![image](https://private-user-images.githubusercontent.com/62510338/388437357-fd4479e1-ae8a-4a83-aea8-f2663025f4d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMzcxNjgsIm5iZiI6MTczMzIzNjg2OCwicGF0aCI6Ii82MjUxMDMzOC8zODg0MzczNTctZmQ0NDc5ZTEtYWU4YS00YTgzLWFlYTgtZjI2NjMwMjVmNGQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDE0NDEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MzRmODVmMmQ0YmMzNDdjMTUwNWM3ZDZjNDEwMzgzNTI4ODNjNTVjN2VhZWEzOTY4Zjk4ZGZjZTFhN2M4OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.grIdXWe5SsUEoP40CxT_ngSwodW9eExYOil3qUZdUBk)



> 你好：感谢你的优秀工作！ readme中可以看到暗光增强和强光抑制分别作为两个部分进行测试，[Decomposition3](https://github.com/jinyeying/night-enhancement/blob/main/decomposition_code/demo_decomposition.m)这里面写到运行demo_decomposition.m可以获得J-init 请问如何直接通过输入得到强光抑制和暗光增强的输出J-refine呢，正如您在论文里面提到的结构图 ![image](https://private-user-images.githubusercontent.com/62510338/388437357-fd4479e1-ae8a-4a83-aea8-f2663025f4d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMzcxNjgsIm5iZiI6MTczMzIzNjg2OCwicGF0aCI6Ii82MjUxMDMzOC8zODg0MzczNTctZmQ0NDc5ZTEtYWU4YS00YTgzLWFlYTgtZjI2NjMwMjVmNGQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDE0NDEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MzRmODVmMmQ0YmMzNDdjMTUwNWM3ZDZjNDEwMzgzNTI4ODNjNTVjN2VhZWEzOTY4Zjk4ZGZjZTFhN2M4OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.grIdXWe5SsUEoP40CxT_ngSwodW9eExYOil3qUZdUBk)

不好意思回复晚了, 我的做法比较简单粗暴, 就是这种效果好的(没光效应的)图片我输入给testB,有光效应的输入给testA, 然后去训练translation网络

**Comment by Bruce-W12138** [comment]
您好作者，这个训练代码是否有问题，我按照您给出的方式设置了trainA和trainB但是仍然报错
‘Traceback (most recent call last):
  File "D:\WorkProject\Image_Enhancement\night-enhancement-main\ENHANCENET.py", line 156, in train
    real_A, _ = trainA_iter.next()
UnboundLocalError: local variable 'trainA_iter' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WorkSoftware\Install\PyCharm Community Edition 2024.1.3\plugins\python-ce\helpers\pydev\pydevd.py", line 1546, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\WorkSoftware\Install\PyCharm Community Edition 2024.1.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:\WorkProject\Image_Enhancement\night-enhancement-main\main.py", line 75, in <module>
    main()
  File "D:\WorkProject\Image_Enhancement\night-enhancement-main\main.py", line 71, in main
    gan.train()
  File "D:\WorkProject\Image_Enhancement\night-enhancement-main\ENHANCENET.py", line 159, in train
    real_A, _ = trainA_iter.next()
AttributeError: '_SingleProcessDataLoaderIter' object has no attribute 'next'’
