### ISSUE TITLE
Save the glow layer image and the low-light image after light effect suppression?

### ISSUE THREAD

**Issue by WuWanyu98** [jinyeying/night-enhancement#3]
Excellent work, thank you very much for your outstanding contribution to this paper!

Here I have a question and would appreciate your help. When testing my own dataset, I wish to save the glow layer images obtained from the decomposition as well as the low light images after the light effect suppression, how can I do that?

**Comment by jinyeying** [comment]
> Excellent work, thank you very much for your outstanding contribution to this paper!
> 
> Here I have a question and would appreciate your help. When testing my own dataset, I wish to save the glow layer images obtained from the decomposition as well as the low light images after the light effect suppression, how can I do that?

Hi,
Thank you for your interest in our works.
If you want the details, you can contact my email sent by your affiliation email with your signed name.

**Comment by Nozomeister** [comment]
> > Excellent work, thank you very much for your outstanding contribution to this paper!
> > Here I have a question and would appreciate your help. When testing my own dataset, I wish to save the glow layer images obtained from the decomposition as well as the low light images after the light effect suppression, how can I do that?
> 
> Hi, Thank you for your interest in our works. If you want the details, you can contact my email sent by your affiliation email with your signed name.

Hi, I am also interest in the image decomposition step and result. Can I contact you for the works? 
Thank you.

**Comment by jinyeying** [comment]
> contact my email sent by your affiliation email with your signed name.

Sure, please contact my email sent by your affiliation email with your signed name.

**Comment by WuWanyu98** [comment]
> > Excellent work, thank you very much for your outstanding contribution to this paper!
> > Here I have a question and would appreciate your help. When testing my own dataset, I wish to save the glow layer images obtained from the decomposition as well as the low light images after the light effect suppression, how can I do that?
> 
> Hi, Thank you for your interest in our works. If you want the details, you can contact my email sent by your affiliation email with your signed name.

OK, I have sent the email, thank you very much for your reply！
