### ISSUE TITLE
如何通过输入I获得分解后的R、L、G呢，层分解网络在ENHANCENET中并没有体现

### ISSUE THREAD

**Issue by swjtu-ljc** [jinyeying/night-enhancement#30]
感谢您的优秀工作和耐心解答！我看到您在readme中提到层分解的三个demo，Decomposition1和Decomposition2都是通过网络使用无监督损失训练得到光照抑制后的图像，Decomposition3是通过matlab代码分离出G和Jinit，层分解网络在ENHANCENET这个网络中并没有用到，正如您在下图所示，分解后的图像输入到GAN中进行对抗训练
我有两个问题期待您的解答：
1.如何直接通过输入I获得分解后的R、L、G呢？
2.如果没有光效好和光效差的图像对输入到GAN中，可以按照图2所示直接输入一张图像进行训练，然后得到抑制后的图像吗？
![image](https://github.com/user-attachments/assets/ed0ca718-f08e-4147-acfa-426809dab45d)

**Comment by jinyeying** [comment]
> 感谢您的优秀工作和耐心解答！我看到您在readme中提到层分解的三个demo，Decomposition1和Decomposition2都是通过网络使用无监督损失训练得到光照抑制后的图像，Decomposition3是通过matlab代码分离出G和Jinit，层分解网络在ENHANCENET这个网络中并没有用到，正如您在下图所示，分解后的图像输入到GAN中进行对抗训练 我有两个问题期待您的解答： 1.如何直接通过输入I获得分解后的R、L、G呢？ 2.如果没有光效好和光效差的图像对输入到GAN中，可以按照图2所示直接输入一张图像进行训练，然后得到抑制后的图像吗？ ![image](https://private-user-images.githubusercontent.com/62510338/393238137-ed0ca718-f08e-4147-acfa-426809dab45d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MjQ4NzEsIm5iZiI6MTczMzcyNDU3MSwicGF0aCI6Ii82MjUxMDMzOC8zOTMyMzgxMzctZWQwY2E3MTgtZjA4ZS00MTQ3LWFjZmEtNDI2ODA5ZGFiNDVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDA2MDkzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyYTc4OTI5MjRiNWViZjIzYjJmOTAxZTY2NDQwODhiYTk2NmQ2ZDViZTE0ZGRjM2M2Y2RiZTM4NTAwNzgzNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0hiMFz2ctzFY4t60wuvQkqhCDTHnnWyzt4ynGmyBAyI)

1. Decomposition3是通过matlab代码分离出R、L、G, post = true试试
https://github.com/jinyeying/night-enhancement/blob/2a0681eae7c2bbc120a019d5bb71bcbd12291df7/decomposition_code/demo_decomposition.m#L23

2. 这种GAN-based的translation网络,是需要图像对的哈

**Comment by swjtu-ljc** [comment]
感谢您的解答，还有一个疑问就是论文中输入图像是经过层分解网络得到R、L、G的，然后再输入到GAN中，但是代码中好像并没有体现层分解的过程，请问除了通过matlab代码还有其他方式得到R、L、G吗？

**Comment by jinyeying** [comment]
> Decomposition1
就是你看到的Decomposition的代码呀, 分解后重要的Jinit和I 输入translation网络

**Comment by swjtu-ljc** [comment]
好的，了解，您指的是demo.py中通过Net这个层分解网络通过无监督损失训练，处理输入之后再输入到GAN中训练是嘛？

**Comment by jinyeying** [comment]
> 好的，了解，您指的是demo.py中通过Net这个层分解网络通过无监督损失训练，处理输入之后再输入到GAN中训练是嘛？

是的

**Comment by create-li** [comment]
@jinyeying @swjtu-ljc 您们好，关于光效应去除训练的数据集怎么制作和流程，我的理解请您们看下对不对：
①本文提出了三种光效应抑制算法，这三种是分开的，其中Decomposition1和Decomposition2是无监督损失学习的。Decomposition3是非配对训练是学习的是吗？
②Decomposition3的训练数据输入是trainA和trainB，分别是光效应和非光效应。trainA是demo_decomposition.m脚本预处理后，获得Jint_trainA和G_trainA,然后将trianA（Jint_trainA和G_trainA）和TrainB送入到ENHANCENET网络训练对吗？
③还是ENHANCENET的网络的输入数据是Decomposition1，Decomposition2，Decomposition3任何一个分解出来的Jint_trainA和G_trainA ，作为训练的输入数据？ 
期待您们的回复

**Comment by jinyeying** [comment]
核心思路就是trainA有光晕，trainB无光晕，不论你用哪个unsupervised的decomposation，只要得到效果好的，就放在trainB去训练

**Comment by create-li** [comment]
> 核心思路就是trainA有光晕，trainB无光晕，不论你用哪个unsupervised的decomposation，只要得到效果好的，就放在trainB去训练


按照您的说话，trainB是基于trainA处理抑制后选择最好的的无光晕图像，这不是有监督学习了吗？
