### ISSUE TITLE
I encounter some bug when  run "python main.py"

### ISSUE THREAD

**Issue by buwangchuxin1992** [jinyeying/night-enhancement#4]
1、syntax error in ENHANCEMENT.py in  line 28.  "self.dom_weight = args.dom_weight" .When I change to "  self.dom_weight =args.atten_weight",there is no error.
2、After fixed bug of question1,when I test use pre-trained LOL model,It seems no effect on image with light from LED data.Why this happens?Is this pre training model not the model in the paper？

**Comment by KKKLeouee** [comment]
> 1、syntax error in ENHANCEMENT.py in line 28. "self.dom_weight = args.dom_weight" .When I change to " self.dom_weight =args.atten_weight",there is no error. 2、After fixed bug of question1,when I test use pre-trained LOL model,It seems no effect on image with light from LED data.Why this happens?Is this pre training model not the model in the paper？

Hello, I see that you are also studying this aspect. I am also studying the topic in this direction recently. Can you add friends and discuss with each other?

My email is: 956358300@qq.com

Please forgive me for interrupting

**Comment by jinyeying** [comment]
> 1、syntax error in ENHANCEMENT.py in line 28. "self.dom_weight = args.dom_weight" .When I change to " self.dom_weight =args.atten_weight",there is no error. 2、After fixed bug of question1,when I test use pre-trained LOL model,It seems no effect on image with light from LED data.Why this happens?Is this pre training model not the model in the paper？

1. a small and fixed bug
2. There are two tasks in our paper, one is the low-light enhancement (LOL), and another one is light-effects suppression (LED data), these two are different training data and checkpoints.

**Comment by buwangchuxin1992** [comment]
> > 1、syntax error in ENHANCEMENT.py in line 28. "self.dom_weight = args.dom_weight" .When I change to " self.dom_weight =args.atten_weight",there is no error. 2、After fixed bug of question1,when I test use pre-trained LOL model,It seems no effect on image with light from LED data.Why this happens?Is this pre training model not the model in the paper？
> 
> 1. a small and fixed bug
> 2. There are two tasks in our paper, one is the low-light enhancement (LOL), and another one is light-effects suppression (LED data), these two are different training data and checkpoints.

Thank you very much.As you said,When get Light-Effects Suppression Results,you should run "python demo.py",but  I find no demo.py.Is this file no upload?thanks

**Comment by KKKLeouee** [comment]
> > 1、ENHANCEMENT.py第28行语法错误。“self.dom_weight = args.dom_weight”。当我改为“self.dom_weight =args.atten_weight”时，没有错误。2、修复问题1的bug后，当我使用预训练的LOL模型进行测试时，从LED数据来看，似乎对图像没有影响。为什么会出现这种情况？这个预训练模型不是论文中的模型吗？
> 
> 1. 一个小而固定的错误
> 2. 我们的论文中有两个任务，一个是低光增强（LOL），另一个是光效抑制（LED数据），这两个是不同的训练数据和检查点。

Hello, I happened to see that you are also paying attention to some underlying image processing work such as light suppression. I am also studying this direction at present. Can I add a contact information to explore each other

My email is: 956358300@qq.com

Please forgive me for interrupting.

I look forward to your reply
