### ISSUE TITLE
It seems no demo.py files

### ISSUE THREAD

**Issue by buwangchuxin1992** [jinyeying/night-enhancement#5]
1、syntax error in ENHANCEMENT.py in line 28. "self.dom_weight = args.dom_weight" .When I change to " self.dom_weight =args.atten_weight",there is no error. 2、After fixed bug of question1,when I test use pre-trained LOL model,It seems no effect on image with light from LED data.Why this happens?Is this pre training model not the model in the paper？

a small and fixed bug
There are two tasks in our paper, one is the low-light enhancement (LOL), and another one is light-effects suppression (LED data), these two are different training data and checkpoints.
Thank you very much.As you said,When get Light-Effects Suppression Results,you should run "python demo.py",but I find no demo.py.Is this file no upload?thanks

**Comment by jinyeying** [comment]
released
