### ISSUE TITLE
I can not find demo.py

### ISSUE THREAD

**Issue by Nukaliad** [jinyeying/night-enhancement#7]
Thank you for your great work!

I want to test the light effect suppression module in your paper. However, I can not find the demo.py. Where can I get it?
Aslo, while testing test_VGGfeatures.py, I can not generate Jrefine.png with the matlab code. I want to know how to generate it?

Thanks!

**Comment by jinyeying** [comment]
> Thank you for your great work!
> 
> I want to test the light effect suppression module in your paper. However, I can not find the demo.py. Where can I get it? Aslo, while testing test_VGGfeatures.py, I can not generate Jrefine.png with the matlab code. I want to know how to generate it?
> 
> Thanks!

Hi, Jrefine.png is the output of our network. It is not from the MATLAB code.

**Comment by Nukaliad** [comment]
Hi, thank you for your reply! It is said that Jrefine.png is generated by the Model-Based Layer Decomposition Network. However, I cannot find its code. Where can I find this module?

**Comment by jinyeying** [comment]
> Hi, thank you for your reply! It is said that Jrefine.png is generated by the Model-Based Layer Decomposition Network. However, I cannot find its code. Where can I find this module?
Thank you for your interest in our work. 
Our layer decomposition is the network implementation of this paper “Single image layer separation using relative smoothness”.

**Comment by Nukaliad** [comment]
Thank you so much! I will try it.

**Comment by clcllllll** [comment]
I can not find the demo.py., so can the program only complete the function of low light enhancement?😂
