### ISSUE TITLE
train in LOL test in LOL_real

### ISSUE THREAD

**Issue by wangchx67** [jinyeying/night-enhancement#8]
LOL dataset has three versions, one  is LOL_V1, which contain 485 training images and 15 testing images, one is LOL_V2_real, which contain 689 training images and 100 testing image, the rest one is LOL_V2_sys, which contains systhetic low-light image. However, LOL_V1 and LOL_V2 are different splits in same datasets, that means LOL_V1's training images contain LOL_V2_real's testing image, if you want to evaluate in LOL_V2_real testing images, I think you should re-train in LOL_V2_real's training image, instead of training in LOL_V1 and testing in LOL_V2_real.

**Comment by jinyeying** [comment]
> LOL dataset has three versions, one is LOL_V1, which contain 485 training images and 15 testing images, one is LOL_V2_real, which contain 689 training images and 100 testing image, the rest one is LOL_V2_sys, which contains systhetic low-light image. However, LOL_V1 and LOL_V2 are different splits in same datasets, that means LOL_V1's training images contain LOL_V2_real's testing image, if you want to evaluate in LOL_V2_real testing images, I think you should re-train in LOL_V2_real's training image, instead of training in LOL_V1 and testing in LOL_V2_real.

Thanks for the information. We follow the experiment settings of AAAI22 Low-light image enhancement with normalizing flow. I did not notice LOL_V1's training images contain LOL_V2_real's testing image. 
Follow the suggestion, I will re-train in LOL_V2_real's training image, and testing in LOL_V2_real.

**Comment by wangchx67** [comment]
You are welcome for it.&nbsp; &nbsp;I experimented in LOLv2_real recently, and I also found pretrain in LOLv1 will perform very well in LOLv2_real.&nbsp;
If you complete retraining in LOLv2_real, can you share new results (enhanced images and new psnr, ssim) with me？
Besides, I want to know if other your paper's compared methods in LOLv2_real is retrain in LOLv2_real, if it is, can you share the results (the enhanced images) with me？ I try to retrain some methods in LOLv2_real, but the reaults are different with the CVPR2022 "&nbsp; SNR-Aware Low-light Image Enhancement ". And the environments of some method are hard to install, I will be very appreciate if you can provide me some results.


Beat wishes.

--------------原始邮件--------------
发件人："AuAgCu ***@***.***&gt;;
发送时间：2022年9月5日(星期一) 下午5:25
收件人："jinyeying/night-enhancement" ***@***.***&gt;;
抄送："王晨曦 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [jinyeying/night-enhancement] train in LOL test in LOL_real (Issue #8)
-----------------------------------

 

  
LOL dataset has three versions, one is LOL_V1, which contain 485 training images and 15 testing images, one is LOL_V2_real, which contain 689 training images and 100 testing image, the rest one is LOL_V2_sys, which contains systhetic low-light image. However, LOL_V1 and LOL_V2 are different splits in same datasets, that means LOL_V1's training images contain LOL_V2_real's testing image, if you want to evaluate in LOL_V2_real testing images, I think you should re-train in LOL_V2_real's training image, instead of training in LOL_V1 and testing in LOL_V2_real.
  
Thanks for the information. We follow the experiment settings of AAAI22 Low-light image enhancement with normalizing flow. I did not notice LOL_V1's training images contain LOL_V2_real's testing image.
 Follow the suggestion, I will re-train in LOL_V2_real's training image, and testing in LOL_V2_real.

**Comment by jinyeying** [comment]
> You are welcome for it.&nbsp; &nbsp;I experimented in LOLv2_real recently, and I also found pretrain in LOLv1 will perform very well in LOLv2_real.&nbsp; If you complete retraining in LOLv2_real, can you share new results (enhanced images and new psnr, ssim) with me？ Besides, I want to know if other your paper's compared methods in LOLv2_real is retrain in LOLv2_real, if it is, can you share the results (the enhanced images) with me？ I try to retrain some methods in LOLv2_real, but the reaults are different with the CVPR2022 "&nbsp; SNR-Aware Low-light Image Enhancement ". And the environments of some method are hard to install, I will be very appreciate if you can provide me some results. Beat wishes.
> […](#)
> --------------原始邮件-------------- 发件人："AuAgCu ***@***.***&gt;; 发送时间：2022年9月5日(星期一) 下午5:25 收件人："jinyeying/night-enhancement" ***@***.***&gt;; 抄送："王晨曦 ***@***.***&gt;;"Author ***@***.***&gt;; 主题：Re: [jinyeying/night-enhancement] train in LOL test in LOL_real (Issue #8) ----------------------------------- LOL dataset has three versions, one is LOL_V1, which contain 485 training images and 15 testing images, one is LOL_V2_real, which contain 689 training images and 100 testing image, the rest one is LOL_V2_sys, which contains systhetic low-light image. However, LOL_V1 and LOL_V2 are different splits in same datasets, that means LOL_V1's training images contain LOL_V2_real's testing image, if you want to evaluate in LOL_V2_real testing images, I think you should re-train in LOL_V2_real's training image, instead of training in LOL_V1 and testing in LOL_V2_real. Thanks for the information. We follow the experiment settings of AAAI22 Low-light image enhancement with normalizing flow. I did not notice LOL_V1's training images contain LOL_V2_real's testing image. Follow the suggestion, I will re-train in LOL_V2_real's training image, and testing in LOL_V2_real. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Sure, once I complete retraining in LOLv2_real, I will share new results (enhanced images and new psnr, ssim) in this GitHub.

We did not have results for SNR-Aware Low-light Image Enhancement.

**Comment by jinyeying** [comment]
> You are welcome for it.&nbsp; &nbsp;I experimented in LOLv2_real recently, and I also found pretrain in LOLv1 will perform very well in LOLv2_real.&nbsp; If you complete retraining in LOLv2_real, can you share new results (enhanced images and new psnr, ssim) with me？ Besides, I want to know if other your paper's compared methods in LOLv2_real is retrain in LOLv2_real, if it is, can you share the results (the enhanced images) with me？ I try to retrain some methods in LOLv2_real, but the reaults are different with the CVPR2022 "&nbsp; SNR-Aware Low-light Image Enhancement ". And the environments of some method are hard to install, I will be very appreciate if you can provide me some results. Beat wishes.
> […](#)
> --------------原始邮件-------------- 发件人："AuAgCu ***@***.***&gt;; 发送时间：2022年9月5日(星期一) 下午5:25 收件人："jinyeying/night-enhancement" ***@***.***&gt;; 抄送："王晨曦 ***@***.***&gt;;"Author ***@***.***&gt;; 主题：Re: [jinyeying/night-enhancement] train in LOL test in LOL_real (Issue #8) ----------------------------------- LOL dataset has three versions, one is LOL_V1, which contain 485 training images and 15 testing images, one is LOL_V2_real, which contain 689 training images and 100 testing image, the rest one is LOL_V2_sys, which contains systhetic low-light image. However, LOL_V1 and LOL_V2 are different splits in same datasets, that means LOL_V1's training images contain LOL_V2_real's testing image, if you want to evaluate in LOL_V2_real testing images, I think you should re-train in LOL_V2_real's training image, instead of training in LOL_V1 and testing in LOL_V2_real. Thanks for the information. We follow the experiment settings of AAAI22 Low-light image enhancement with normalizing flow. I did not notice LOL_V1's training images contain LOL_V2_real's testing image. Follow the suggestion, I will re-train in LOL_V2_real's training image, and testing in LOL_V2_real. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Hi, I have updated LOL_v2_real results (enhanced images and new psnr, ssim) in this GitHub (see update).
